name: mobile_happify
description: Happify mobile wellbeing companion.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluentui_emoji_icon: ^0.0.2
  go_router: ^17.3.0
  google_fonts: ^8.1.0
  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.3.0
  flutter_animate: ^4.5.2
  flutter_tts: ^4.2.5
  audioplayers: ^6.7.1
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  firebase_messaging: ^16.4.1
  dio: ^5.10.0
  record: ^6.2.1
  shared_preferences: ^2.5.4
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  bloc_test: ^10.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/mascot/happify-app-icon.png
  adaptive_icon_background: "#FFF8E8"
  adaptive_icon_foreground: assets/mascot/happify-app-icon.png
  adaptive_icon_foreground_inset: 16
  remove_alpha_ios: true
  background_color_ios: "#FFF8E8"

flutter:
  uses-material-design: true
  assets:
    - assets/mascot/
    - assets/illustrations/
    - assets/animations/
